name: Family_Tree_App
description: Family Tree App
publish_to: 'none' 
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.1.12
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
